name: Run Python Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # 指定Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 如果有依赖可以在这里安装

    - name: Run script
      run: python 21.py
      # 这里假设1.py不需要额外的命令行参数
